version: 0.4.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
cache: src/packages
before_build:
- dotnet restore src/Takenet.Elephant.sln
after_build:
- dotnet pack src/Takenet.Elephant/Takenet.Elephant.csproj --no-build --configuration Release /p:Version={version}
- dotnet pack src/Takenet.Elephant.Msmq/Takenet.Elephant.Msmq.csproj --no-build --configuration Release /p:Version={version}
- dotnet pack src/Takenet.Elephant.Redis/Takenet.Elephant.Redis.csproj --no-build --configuration Release /p:Version={version}
- dotnet pack src/Takenet.Elephant.Sql/Takenet.Elephant.Sql.csproj --no-build --configuration Release /p:Version={version}
- dotnet pack src/Takenet.Elephant.Sql.PostgreSql/Takenet.Elephant.Sql.PostgreSql.csproj --no-build --configuration Release /p:Version={version}
- dotnet pack src/Takenet.Elephant.Specialized/Takenet.Elephant.Specialized.csproj --no-build --configuration Release /p:Version={version}
branches:
  only:
    - master
build:
  project: src/Takenet.Elephant.sln
  verbosity: minimal
test:
  categories:
    only:
      - Memory
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_file_version: '{version}'
  assembly_version: '{version}'
  assembly_informational_version: '{version}'
artifacts:
  - path: Takenet.Elephant.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: 0huvVwDjQ/i7FNOrby1sd/KJ1NaSFNOmTh4uUuS/kp7K7W2O3sDdnEeeYz8MwAzb
  skip_symbols: true