version: 0.7.{build}
image: Visual Studio 2019
configuration: Release
platform: Any CPU
cache: src/packages
branches:
  only:
    - master
before_build:
- dotnet restore src/Take.Elephant.sln
build:
  parallel: true
  project: src/Take.Elephant.sln
  verbosity: minimal
after_build:
- dotnet pack src/Take.Elephant/Take.Elephant.csproj --configuration Release /p:Version=%APPVEYOR_BUILD_VERSION%
- dotnet pack src/Take.Elephant.Redis/Take.Elephant.Redis.csproj --configuration Release /p:Version=%APPVEYOR_BUILD_VERSION%
- dotnet pack src/Take.Elephant.Sql/Take.Elephant.Sql.csproj --configuration Release /p:Version=%APPVEYOR_BUILD_VERSION%
- dotnet pack src/Take.Elephant.Sql.PostgreSql/Take.Elephant.Sql.PostgreSql.csproj --configuration Release /p:Version=%APPVEYOR_BUILD_VERSION%
- dotnet pack src/Take.Elephant.Specialized/Take.Elephant.Specialized.csproj --configuration Release /p:Version=%APPVEYOR_BUILD_VERSION%
- dotnet pack src/Take.Elephant.Azure/Take.Elephant.Azure.csproj --configuration Release /p:Version=%APPVEYOR_BUILD_VERSION%
- dotnet pack src/Take.Elephant.Kafka/Take.Elephant.Kafka.csproj --configuration Release /p:Version=%APPVEYOR_BUILD_VERSION%
- dotnet pack src/Take.Elephant.Elasticsearch/Take.Elephant.Elasticsearch.csproj --configuration Release /p:Version=%APPVEYOR_BUILD_VERSION%
services:
  - msmq
test: off
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_file_version: '{version}'
  assembly_version: '{version}'
  assembly_informational_version: '{version}'
artifacts:
  - path: '**\Take.Elephant*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: IXFmfWSIex9pLNAX4Ezrh+BLb8rNnUC43w9gfIXAVpx4TB1aE5g2/ffivh5mYwRz
  skip_symbols: true
