version: 0.5.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
cache: src/packages
branches:
  only:
    - master
before_build:
- dotnet restore src/Takenet.Elephant.sln
build:
  parallel: true
  project: src/Takenet.Elephant.sln
  verbosity: minimal
after_build:
- dotnet pack src/Takenet.Elephant/Takenet.Elephant.csproj --configuration Release /p:Version=%APPVEYOR_BUILD_VERSION%
- dotnet pack src/Takenet.Elephant.Msmq/Takenet.Elephant.Msmq.csproj --configuration Release /p:Version=%APPVEYOR_BUILD_VERSION%
- dotnet pack src/Takenet.Elephant.Redis/Takenet.Elephant.Redis.csproj --configuration Release /p:Version=%APPVEYOR_BUILD_VERSION%
- dotnet pack src/Takenet.Elephant.Sql/Takenet.Elephant.Sql.csproj --configuration Release /p:Version=%APPVEYOR_BUILD_VERSION%
- dotnet pack src/Takenet.Elephant.Sql.PostgreSql/Takenet.Elephant.Sql.PostgreSql.csproj --configuration Release /p:Version=%APPVEYOR_BUILD_VERSION%
- dotnet pack src/Takenet.Elephant.Specialized/Takenet.Elephant.Specialized.csproj --configuration Release /p:Version=%APPVEYOR_BUILD_VERSION%
- dotnet pack src/Takenet.Elephant.Azure/Takenet.Elephant.Azure.csproj --configuration Release /p:Version=%APPVEYOR_BUILD_VERSION%
services:
  - msmq
test: off
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_file_version: '{version}'
  assembly_version: '{version}'
  assembly_informational_version: '{version}'
artifacts:
  - path: '**\Takenet.Elephant*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: 0huvVwDjQ/i7FNOrby1sd/KJ1NaSFNOmTh4uUuS/kp7K7W2O3sDdnEeeYz8MwAzb
  skip_symbols: true