version: 0.4.{build}
configuration: Release
platform: Any CPU
cache: src/packages
before_build:
- nuget restore src/Takenet.Elephant.sln
after_build:
- nuget pack src/Takenet.Elephant/Takenet.Elephant.csproj -Symbols -Properties Configuration=Release -Properties Platform=AnyCPU
- nuget pack src/Takenet.Elephant.MongoDB/Takenet.Elephant.MongoDB.csproj -Symbols -Properties Configuration=Release -Properties Platform=AnyCPU
- nuget pack src/Takenet.Elephant.RabbitMQ/Takenet.Elephant.RabbitMQ.csproj -Symbols -Properties Configuration=Release -Properties Platform=AnyCPU
- nuget pack src/Takenet.Elephant.Redis/Takenet.Elephant.Redis.csproj -Symbols -Properties Configuration=Release -Properties Platform=AnyCPU
- nuget pack src/Takenet.Elephant.SQL/Takenet.Elephant.SQL.csproj -Symbols -Properties Configuration=Release -Properties Platform=AnyCPU
- nuget pack src/Takenet.Elephant.Specialized/Takenet.Elephant.Specialized.csproj -Symbols -Properties Configuration=Release -Properties Platform=AnyCPU
build:
  project: src/Takenet.Elephant.sln
  verbosity: minimal
environment:
  RABBITMQ_HOSTNAME: moose.rmq.cloudamqp.com 
  RABBITMQ_VHOST: vujfyubs
  RABBITMQ_USERNAME: vujfyubs
  RABBITMQ_PASSWORD:
    secure: LZ+N9GVdMnpX36sLaNih/Lu3yIlWrUA0A3w7lk5T2jj2v6Zy44oL5480ZNVoYhhe
  REDIS_ENDPOINT:
    secure: X9Qr+1WDAWhpsxTa3bEFTvtjCQwxgsF4rtat9ItJBNsularweTRUbJlq358Ofkn6iGkkjJb22gwr7dd2oikSsAa5nnanbRyqTmQX4SaXUMQ=
test:
  categories:
    except:
      - suppressed
assembly_info:
  patch: true
  file: src\Takenet.Elephant\Properties\AssemblyInfo.cs
  assembly_file_version: '{version}'
  assembly_version: '{version}'
  assembly_informational_version: '{version}'
artifacts:
  - path: Takenet.Elephant.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: 0huvVwDjQ/i7FNOrby1sd/KJ1NaSFNOmTh4uUuS/kp7K7W2O3sDdnEeeYz8MwAzb
  skip_symbols: false