version: 0.4.{build}
configuration: Release
platform: Any CPU
cache: src/packages
before_build:
- nuget restore src/Takenet.Elephant.sln
after_build:
- nuget pack src/Takenet.Elephant/Takenet.Elephant.csproj -Symbols -Properties Configuration=Release -Properties Platform=AnyCPU
- nuget pack src/Takenet.Elephant.RabbitMQ/Takenet.Elephant.RabbitMQ.csproj -Symbols -Properties Configuration=Release -Properties Platform=AnyCPU
- nuget pack src/Takenet.Elephant.Msmq/Takenet.Elephant.Msmq.csproj -Symbols -Properties Configuration=Release -Properties Platform=AnyCPU
- nuget pack src/Takenet.Elephant.Redis/Takenet.Elephant.Redis.csproj -Symbols -Properties Configuration=Release -Properties Platform=AnyCPU
- nuget pack src/Takenet.Elephant.Sql/Takenet.Elephant.Sql.csproj -Symbols -Properties Configuration=Release -Properties Platform=AnyCPU
- nuget pack src/Takenet.Elephant.Sql.PostgreSql/Takenet.Elephant.Sql.PostgreSql.csproj -Symbols -Properties Configuration=Release -Properties Platform=AnyCPU
- nuget pack src/Takenet.Elephant.Specialized/Takenet.Elephant.Specialized.csproj -Symbols -Properties Configuration=Release -Properties Platform=AnyCPU
branches:
  only:
    - master
build:
  project: src/Takenet.Elephant.sln
  verbosity: minimal
test:
  categories:
    only:
      - ok
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_file_version: '{version}'
  assembly_version: '{version}'
  assembly_informational_version: '{version}'
artifacts:
  - path: Takenet.Elephant.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: 0huvVwDjQ/i7FNOrby1sd/KJ1NaSFNOmTh4uUuS/kp7K7W2O3sDdnEeeYz8MwAzb
  skip_symbols: true